name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci  # Install dependencies

      - name: Build static site
        run: |
          npm run build  # Build your app
          cp dist/public/index.html dist/public/404.html  # Handle client-side routing
          touch dist/public/.nojekyll  # Disable Jekyll processing to avoid conflicts

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/public  # Path to the folder containing your static assets

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # URL of the deployed page
    runs-on: ubuntu-latest
    needs: build  # Ensure deployment only happens after successful build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
